import './manager-action-apply/enqueue-dedupe-scenarios.js'
import './manager-action-apply/mutate-choice-scenarios.js'
import './manager-action-apply/plan-scenarios.js'
import './manager-action-apply/focus-scenarios.js'
import './manager-action-apply/memory-scenarios.js'
