export const TASK_SCHEMA_VERSION = 2
export const TRIGGER_SCHEMA_VERSION = 2
export const PLANNER_RESULT_SCHEMA_VERSION = 2
export const WORKER_RESULT_SCHEMA_VERSION = 2
export const TASK_STATUS_SCHEMA_VERSION = 2
